apiVersion: apps/v1
kind: Deployment
metadata:
  name:  api
  namespace: workshop
  labels:
    role:  api
    env: demo
spec:
  selector:
    matchLabels:
      app: api
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api  
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  api
        image: 760711518955.dkr.ecr.us-east-1.amazonaws.com/three-tier-backend
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        #   limits:
        #     cpu: 100m
        #     memory: 100Mi
        ports:
        - containerPort:  8080
        livenessProbe:
          httpGet:
            path: /ok
            port: 8080
          # tcpSocket:
          #   port: 80
          initialDelaySeconds: 2
          # timeoutSeconds: 5
          # successThreshold: 1
          # failureThreshold: 3
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ok
            port: 8080
          initialDelaySeconds: 5
          # timeoutSeconds: 2
          successThreshold: 1
          # failureThreshold: 3
          periodSeconds: 5
        env:
        - name: MONGO_CONN_STR
          value:  mongodb://mongodb-svc:27017/todo?directConnection=true

        - name: MONGO_USERNAME
          valueFrom:
           secretKeyRef:
            name: mongo-sec
            key: username

        - name: MONGO_PASSWORD
          valueFrom:
           secretKeyRef:
            name: mongo-sec
            key: password  
        
        
          
      #   volumeMounts:
      #   - name: localtime
      #     mountPath: /etc/localtime
      # volumes:
      #   - name: localtime
      #     hostPath:
      #       path: /usr/share/zoneinfo/Asia/Shanghai
      # restartPolicy: Always
